org.gradle.jvmargs=-Xmx2G
modName=MoogsSoaringStructures
minecraftVersion=1.20
modVersion=2.1.1
modId=mss
modDescription=Moogs Soaring Structures brings life, fun and variety to your Minecraft world! Explore awesome new structures made with vanilla blocks and entities, and discover loot, enemies, and villagers along the way. This mod is compatible with any modpack and keeps the vanilla feel of the game!
modHomepage=https://www.curseforge.com/minecraft/mc-mods/mss-moogs-soaring-structures
modSources=https://github.com/FinnSetchell/MoogsSoaringStructures
modReleases=https://github.com/FinnSetchell/MoogsSoaringStructures/releases
modIssues=https://github.com/FinnSetchell/MoogsSoaringStructures/issues
modDiscord=https://discord.gg/S5nffJbuvA
modKofi=https://ko-fi.com/finndog
modCurseforge=https://www.curseforge.com/minecraft/mc-mods/mss-moogs-soaring-structures
modModrinth=https://modrinth.com/mod/mss-moogs-soaring-structures

# Structure Lib dependency range (forge mods.toml)
structureLibVersionRange=[1.0.0,)

# Publishing display customization
publishDisplayPrefix=MSS
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=RJCLIx7k
curseforgeProjectId=1040210
curseforgeProjectSlug=mss-moogs-soaring-structures
publishMcStart=1.20
publishMcEnd=1.20.6

# Discord webhook settings
discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/1017/780/64/64/638544186354409472.png
discordEmbedColor=#14822d
discordThumbnailUrl=https://media.forgecdn.net/avatars/thumbnails/1017/780/64/64/638544186354409472.png
discordBannerUrl=https://www.bisecthosting.com/images/CF/Moogs_Soaring_Structure/BH_MSS_header.webp
discordRoleId=1466012771379581039
discordPing=true