org.gradle.jvmargs=-Xmx2G
modName=MoogsSoaringStructures
minecraftVersion=1.20
modVersion=2.0.2
modId=mss
modDescription=Moogs Soaring Structures brings life, fun and variety to your Minecraft world! Explore awesome new structures made with vanilla blocks and entities, and discover loot, enemies, and villagers along the way. This mod is compatible with any modpack and keeps the vanilla feel of the game!
modHomepage=https://github.com/FinnSetchell/MoogsSoaringStructures
modSources=https://github.com/FinnSetchell/MoogsSoaringStructures
modIssues=https://github.com/FinnSetchell/MoogsSoaringStructures/issues
structureLibVersionRange=[1.0,)

# Publishing display customization
publishDisplayPrefix=MSS
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=RJCLIx7k
curseforgeProjectId=1040210
publishMcStart=1.20
publishMcEnd=1.20.6